services:
  db:
    image: mysql:8.0
    container_name: shopping-mall-db
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mall_db
    volumes:
      - ./mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: mall-backend
    volumes:
      - ./backend/shopping-mall-api:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mall_db?serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/shopping-mall-web:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    #depends_on:
      #- backend