services:
  db:
    image: mysql:8.0
    container_name: db
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mall_db
    volumes:
      - ./mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend-server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mall_db?serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - TOSS_SECRET_KEY=${TOSS_SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}

  frontend:
    build:
      context: ./frontend
    container_name: frontend-server
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/shopping-mall-web:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - API_INTERNAL_URL=http://backend:8080/api/v1
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    #depends_on:
      #- backend
