spring:
  datasource:
    url: jdbc:mysql://localhost:3307/mall_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operations-sorter: method
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs
  default-consume-media-type: application/json
  default-produce-media-type: application/json


toss:
  payments:
    secret-key: ${TOSS_SECRET_KEY}
    url: https://api.tosspayments.com/v1/payments